### ISSUE TITLE
Migrating from signalfx-tracing to splunk-otel-js Tracer Question 

### ISSUE THREAD

**Issue by rkburnett** [signalfx/splunk-otel-js#216]
Hello, 

I am in the process of migrating from signalfx-tracing to splunk-otel-js.

When using signalfx-tracing, the instrumentation entry point returns `tracer`:

```
const tracer = require('signalfx-tracing').init({
  // your options here
})
```

According to the documentation, the new way of doing this is:
```
const { startTracing } = require('@splunk/otel');

startTracing({
  // your new options here
});
```

It looks like startTracing does not return anything. 

When using the signalfx-tracing library, we depended on the `tracer` object returned from the init function throughout our application (i.e. `tracer.scope()` and `tracer.startSpan()`). 

Can you help me understand how to get the `tracer` object when using splunk-otel-js?

Thanks!

@jtmalinowski

**Comment by jtmalinowski** [comment]
Welcome! `splunk-otel-js`'s purpose it to streamline the configuration process, and help you connect to Splunk Observability quickly, while everything else, like for example manual instrumentation, follows Open Telemetry specification.

A good starting point in your case is <https://github.com/open-telemetry/opentelemetry-js-api/blob/main/docs/tracing.md>.  It might be a bit counter-intuitive in the beginning, but you need to interact with `@opentelemetry/api`, rather than with `@splunk/otel-js`.

This is a very valid issue, and I'll definitely address it in our migration guide, but it may take a couple of days. Also, please do let us know about anything you found unclear in the linked `tracing.md` guide, so we can improve it in addition to improving our guide.

**Comment by rkburnett** [comment]
Thank you for the clarity @jtmalinowski ! 

My only other question is regarding what the correct order needs to be... Does the `@splunk/otel` `startTracing()` function need to be called before interacting with `@opentelemetry/api`? 

i.e.
```
const { startTracing } = require('@splunk/otel');
startTracing(options);

const { trace } = require('@opentelemetry/api');
const tracer = trace.getTracer('my-application', '0.1.0');
```

Thanks again for your help.

**Comment by jtmalinowski** [comment]
Yes, that's correct, `startTracing()` must be called first. That's why we like the `node -r tracing.js app.js` pattern ([like here](https://github.com/signalfx/splunk-otel-js/pull/212/files#diff-f62ad7717bf25934ad572e828c5b6d39fb818d0b780d73b7aab1ea437ab3f222R8)), where `tracing.js` calls `startTracing()` and `app.js` starts your application. It ensures that instrumentation is executed before the application starts.

The tracer returned by `@opentelemetry/api` is different, and it's [this one](https://open-telemetry.github.io/opentelemetry-js-api/interfaces/tracer.html). It doesn't have a `.scope()` method.

I'm assuming that you'd like to access `tracer.scope()` to connect spans together in a trace. The API to achieve that is described in [this paragraph in Open Telemetry docs](https://github.com/open-telemetry/opentelemetry-js-api/blob/main/docs/tracing.md#describing-a-span). Let me highlight the most important parts:

```javascript
import { context, setSpan, trace } from '@opentelemetry/api';

// creates a span but it doesn't become the active span yet
const span = tracer.startSpan(`GET /user/:id`);

// creates a context which is sort of like scope in Open Tracing
const ctx = setSpan(context.active(), span);

// runs your function, which is getUser in this case
// if you call context.active() within getUser, you'll get the ctx from above
// whatever happens within getUser will be linked to your ctx context
context.with(ctx, getUser, undefined, userId);
// or if getUser returns a promise
await context.with(ctx, getUser, undefined, userId);

// always remember to end the span
span.end();
```

As you can see the `scope` from `signalfx-tracing` behaves differently. The process of migration from `signalfx-tracing` to `@splunk/otel` will require more than find-and-replace. We'll be building more example and docs soon.

cc @theletterf @Rauno56

**Comment by theletterf** [comment]
Currently OoO — please report this and other changes through our Docs Jira. Thanks!

**Comment by rkburnett** [comment]
Thank you very much for your help! @jtmalinowski

**Comment by jtmalinowski** [comment]
We're always happy to help!
