### ISSUE TITLE
Starting profiling after tracing Error: @opentelemetry/api: Attempted duplicate registration of API: context

### ISSUE THREAD

**Issue by michi88** [signalfx/splunk-otel-js#534]
When I do:

```js
startTracing(...);
startProfiling(...);
```
I'm getting the error:
```
Error: @opentelemetry/api: Attempted duplicate registration of API: context
    at Object.registerGlobal (.../@opentelemetry/api/build/src/internal/global-utils.js:33:19)
    at ContextAPI.setGlobalContextManager (.../@opentelemetry/api/build/src/api/context.js:49:31)
    at startProfiling (.../@splunk/otel/lib/profiling/index.js:66:19)
    ...
```

It all seems to work but would be good to fix this.

**Comment by seemk** [comment]
This is now fixed in `1.4.1` of `@splunk/otel`. Profiling sets up its own context manager and tracing tried to overwrite it, which OTel doesn't allow, causing a diagnostic error log.

P.S. Profiling needs to be started first. We have a new API coming (https://github.com/signalfx/splunk-otel-js/blob/main/src/start.ts#L47) that fixes the ordering problems.
